INSERT INTO Livros VALUES 
(1, 'Dom Casmurro', 'Machado de Assis',
 1899, 'Romance');

INSERT INTO Livros VALUES
(2, 'O Alquimista', 'Paulo Coelho',
1988, 'Ficção');

INSERT INTO Livros VALUES 
(3, 'Capitão ds Areia', 'Jorge Amado',
1937, 'Drama');

INSERT INTO Livros VALUES
(4, 'O Pequeno Príncipe', 'Antoine ds Saint-Exupéry',
1943, 'Fantasia');

INSERT INTO Livros VALUES 
(5, '1984', 'George Orwell',
 1949, 'Distopia');




INSERT INTO Usuarios values 
(1, 'João Silva', 'joao@gmail.com',
 '823456789');
 
INSERT INTO Usuarios values 
(2, 'Maria Fernandes', 'maria@gmail.com',
 '844567890');
 
 INSERT INTO Usuarios values 
(3, 'Carlos Mendez', 'carlosm@gmail.com',
 '822345678');
 
 INSERT INTO Usuarios values 
(4, 'Ana Oliveira', 'ana.oliveira@gmail.com',
 '847890123');
 
 INSERT INTO Usuarios values 
(5, 'Pedro Santos', 'pedros@gmail.com',
 '823498765');



INSERT INTO Emprestimos values
(1, 1, 3, 2025-01-01, 2025-01-10);

INSERT INTO Emprestimos values
(2, 2, 5, 2025-01-03, 2025-01-13);

INSERT INTO Emprestimos values
(3, 3, 1, 2025-01-05, NULL);

INSERT INTO Emprestimos values
(4, 4, 4, 2025-01-07, NULL);

INSERT INTO Emprestimos values
(5, 5, 2, 2025-01-08, 2025-01-18);