INSERT INTO Usuarios values 
(1, 'João Silva', 'joao@gmail.com',
 '823456789');
 
INSERT INTO Usuarios values 
(2, 'Maria Fernandes', 'maria@gmail.com',
 '844567890');
 
 INSERT INTO Usuarios values 
(3, 'Carlos Mendez', 'carlosm@gmail.com',
 '822345678');
 
 INSERT INTO Usuarios values 
(4, 'Ana Oliveira', 'ana.oliveira@gmail.com',
 '847890123');
 
 INSERT INTO Usuarios values 
(5, 'Pedro Santos', 'pedros@gmail.com',
 '823498765');